name = "FokkerPlanck"
uuid = "6a6b5c72-6869-4c05-b853-2893d318cc38"
authors = ["Michael Hardman <michael.hardman@ukaea.uk>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FiniteElementMatrices = "21a267ae-cf5f-40e4-86cc-2968ca96a734"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JacobianFreeNewtonKrylov = "ea74541f-29a8-443c-83cd-bcc24bd49708"
LagrangePolynomials = "fb83b288-ce1a-45f4-939e-c34c34051e49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[sources]
FiniteElementMatrices = {rev = "main", url = "https://github.com/moment-kinetics/FiniteElementMatrices"}
JacobianFreeNewtonKrylov = {rev = "main", url = "https://github.com/moment-kinetics/JacobianFreeNewtonKrylov"}
LagrangePolynomials = {rev = "main", url = "https://github.com/moment-kinetics/LagrangePolynomials"}

[compat]
FiniteElementMatrices = "0.1.0"
JacobianFreeNewtonKrylov = "0.1.0"
LagrangePolynomials = "0.1.0"
StableRNGs = "1"
julia = "1.9.0"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StableRNGs"]
